version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      - POSTGRES_DB=hydrolink
      - POSTGRES_USER=mario
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    networks:
      - my_network
    restart: unless-stopped

  my_api:
    image: marito11/my_api:latest
    ports:
      - "3000:3000"
    # ¡Elimina todos los volúmenes aquí!
    networks:
      - my_network
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8000:8000"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
