name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DOCKER_COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
          echo "DOCKERFILE=Dockerfile.prod" >> $GITHUB_ENV

      - name: Create and secure .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
          chmod 640 .env  # Permisos balanceados (usuario:lectura+escritura, grupo:lectura)

      - name: Verify files
        run: |
          ls -lh ${{ env.DOCKER_COMPOSE_FILE }} mosquitto.conf .env
          [ $(stat -c %a .env) -eq 640 ] || { echo "ERROR: Permisos incorrectos en .env"; exit 1; }

      - name: Transfer files (safe method)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "${{ env.DOCKER_COMPOSE_FILE }},mosquitto.conf,.env"
          target: "/home/ubuntu/deploy_temp"  # Directorio temporal accesible
          overwrite: true
          strip_components: 0

      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Prepara directorio con permisos
            sudo mkdir -p /opt/hydro-api-v2
            sudo chown -R ubuntu:ubuntu /opt/hydro-api-v2

            # 2. Mueve archivos preservando permisos
            sudo mv /home/ubuntu/deploy_temp/* /opt/hydro-api-v2/
            sudo chmod 640 /opt/hydro-api-v2/.env  # Asegura permisos seguros

            # 3. Limpieza y despliegue
            cd /opt/hydro-api-v2
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down || true
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --build

            # 4. Verificación
            docker ps -a | grep hydro-api
            sudo rm -rf /home/ubuntu/deploy_temp
